import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import UserNavbarComponent from "@/components/UserNavbarComponent";
import { Suspense } from "react";
import Loading from "./loading";

const roboto = Roboto({
	subsets: ["latin"],
	display: "swap",
	weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<UserNavbarComponent />
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	);
}
